
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bryam
 */
public class CrearRutinaFrame extends javax.swing.JFrame {

    /**
     * Creates new form CrearRutinaFrame
     * @param usuario
     */
    public CrearRutinaFrame(Usuarios usuario){
        initComponents();
        nUsuario=usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAbdominales = new javax.swing.JCheckBox();
        btAbdominales = new javax.swing.JButton();
        txtPlancha = new javax.swing.JCheckBox();
        btPlancha = new javax.swing.JButton();
        txtJalon = new javax.swing.JCheckBox();
        btJalon = new javax.swing.JButton();
        txtPress = new javax.swing.JCheckBox();
        btPress = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreRutina = new javax.swing.JTextField();
        botonCreaRutina = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 28)); // NOI18N
        jLabel1.setText("Crear Rutina");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Tren Inferior:");

        txtAbdominales.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtAbdominales.setText("Abdominales");
        txtAbdominales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtAbdominalesMousePressed(evt);
            }
        });
        txtAbdominales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAbdominalesActionPerformed(evt);
            }
        });

        btAbdominales.setText("Ver ejercicio");
        btAbdominales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbdominalesActionPerformed(evt);
            }
        });

        txtPlancha.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtPlancha.setText("Plancha");
        txtPlancha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPlanchaMousePressed(evt);
            }
        });
        txtPlancha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlanchaActionPerformed(evt);
            }
        });

        btPlancha.setText("Ver ejercicio");
        btPlancha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlanchaActionPerformed(evt);
            }
        });

        txtJalon.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtJalon.setText("Jalón al pecho");
        txtJalon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtJalonMousePressed(evt);
            }
        });
        txtJalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJalonActionPerformed(evt);
            }
        });

        btJalon.setText("Ver ejercicio");
        btJalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJalonActionPerformed(evt);
            }
        });

        txtPress.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtPress.setText("Press para hombro");
        txtPress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPressMousePressed(evt);
            }
        });
        txtPress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPressActionPerformed(evt);
            }
        });

        btPress.setText("Ver ejercicio");
        btPress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPressActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Nombre de la rutina:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Zona Media:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Tren Superior:");

        txtNombreRutina.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtNombreRutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreRutinaActionPerformed(evt);
            }
        });

        botonCreaRutina.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        botonCreaRutina.setText("Crear Rutina");
        botonCreaRutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCreaRutinaActionPerformed(evt);
            }
        });

        botonRegresar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(botonCreaRutina)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonRegresar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNombreRutina, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJalon)
                    .addComponent(txtPlancha)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtAbdominales)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAbdominales))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btJalon)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btPress))
                            .addComponent(btPlancha))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAbdominales)
                    .addComponent(btAbdominales))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlancha)
                    .addComponent(btPlancha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJalon)
                    .addComponent(btJalon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPress)
                    .addComponent(btPress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCreaRutina)
                    .addComponent(botonRegresar))
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAbdominalesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAbdominalesMousePressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_txtAbdominalesMousePressed

    private void txtAbdominalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAbdominalesActionPerformed
        // TODO add your handling code here:
        if(txtAbdominales.isSelected()){
            String cantidad=JOptionPane.showInputDialog(null, "Ingrese el número de repeticiones a realizar:", "Cantidad de repeticiones", HEIGHT);
            System.out.println(cantidad);
            if(cantidad==null){
                txtAbdominales.setSelected(false);
            }else{
                try{
                    intCantAbdominales=Integer.parseInt(cantidad.trim());
      
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Las repeticiones solo pueden ser números", "Ingreso inválido", JOptionPane.WARNING_MESSAGE);
                    txtAbdominales.setSelected(false);
                }
            }
        }
    }//GEN-LAST:event_txtAbdominalesActionPerformed

    private void btAbdominalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbdominalesActionPerformed
        // TODO add your handling code here:
        
        InformacionEjercicios abdominales= new InformacionEjercicios("./src/Graficas/ab1.jpg", "./src/Graficas/ab2.jpg", "Abdominales", 
        
        "Se recomienda realizar 50 abdominales en 5 rondas de 10 abdominales cada 1 separados en un lapso de 10 minutos cada ronda."        
        );
        
        abdominales.setVisible(true);
    }//GEN-LAST:event_btAbdominalesActionPerformed

    private void txtPlanchaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPlanchaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlanchaMousePressed

    private void txtPlanchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlanchaActionPerformed
        // TODO add your handling code here:
        if(txtPlancha.isSelected()){
            String cantidad=JOptionPane.showInputDialog(null, "Ingrese los segundos a realizar:", "Cantidad de segundos", HEIGHT);
            System.out.println(cantidad);
            if(cantidad==null){
                txtPlancha.setSelected(false);
            }else{
                try{
                    intTiemPlancha=Integer.parseInt(cantidad.trim());
      
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "El tiempo solo pueden ser en s", "Ingreso inválido", JOptionPane.WARNING_MESSAGE);
                    txtPlancha.setSelected(false);
                }
            }
        }
    }//GEN-LAST:event_txtPlanchaActionPerformed

    private void btPlanchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPlanchaActionPerformed
       InformacionEjercicios plancha= new InformacionEjercicios("./src/Graficas/plancha1.jpg", "./src/Graficas/plancha2.jpg", "Plancha", 
        
        "trabajando por tiempo, entre 12 y 20 segundos en en 6 series."        
        );
        
        plancha.setVisible(true);
    }//GEN-LAST:event_btPlanchaActionPerformed

    private void txtJalonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJalonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJalonMousePressed

    private void txtJalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJalonActionPerformed
        // TODO add your handling code here:
        if(txtJalon.isSelected()){
            String cantidad=JOptionPane.showInputDialog(null, "Ingrese el número de repeticiones a realizar:", "Cantidad de repeticiones", HEIGHT);
            System.out.println(cantidad);
            if(cantidad==null){
                txtJalon.setSelected(false);
            }else{
                try{
                    intCantJalon=Integer.parseInt(cantidad.trim());
      
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Las repeticiones solo pueden ser números", "Ingreso inválido", JOptionPane.WARNING_MESSAGE);
                    txtJalon.setSelected(false);
                }
            }
        }
    }//GEN-LAST:event_txtJalonActionPerformed

    private void btJalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJalonActionPerformed
        // TODO add your handling code here:
        InformacionEjercicios jalon= new InformacionEjercicios("./src/Graficas/jalon1.jpg", "./src/Graficas/jalon2.jpg", "Jalón al pecho", 
        
        "Se realizan 3 series de 20 repeticiones."        
        );
        
        jalon.setVisible(true);
    }//GEN-LAST:event_btJalonActionPerformed

    private void txtPressMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPressMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPressMousePressed

    private void txtPressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPressActionPerformed
        // TODO add your handling code here:
        if(txtPress.isSelected()){
            String cantidad=JOptionPane.showInputDialog(null, "Ingrese el número de repeticiones a realizar:", "Cantidad de repeticiones", HEIGHT);
            System.out.println(cantidad);
            if(cantidad==null){
                txtPress.setSelected(false);
            }else{
                try{
                    intCantPress=Integer.parseInt(cantidad.trim());
      
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Las repeticiones solo pueden ser números", "Ingreso inválido", JOptionPane.WARNING_MESSAGE);
                    txtPress.setSelected(false);
                }
            }
        }
    }//GEN-LAST:event_txtPressActionPerformed

    private void btPressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPressActionPerformed
        InformacionEjercicios jalon= new InformacionEjercicios("./src/Graficas/press1.jpg", "./src/Graficas/press2.jpg", "Press para hombro", 
        
        "12 repeticiones en 4 series."        
        );
        
        jalon.setVisible(true);
    }//GEN-LAST:event_btPressActionPerformed

    private void txtNombreRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreRutinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreRutinaActionPerformed

    private void botonCreaRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCreaRutinaActionPerformed
        // TODO add your handling code here:
        
        
        Rutina nuevaRutina= new Rutina(txtNombreRutina.getText());
          
       if(txtAbdominales.isSelected()){
           nuevaRutina.agregarEjercicio("Abdominales", intCantAbdominales, 0);
          
       }
        if(txtJalon.isSelected()){
           nuevaRutina.agregarEjercicio("Jalón al pecho", intCantJalon, 0);
          
       }
         if(txtPlancha.isSelected()){
           nuevaRutina.agregarEjercicio("Plancha", 0, intTiemPlancha);
          
       }
          if(txtPress.isSelected()){
           nuevaRutina.agregarEjercicio("Press para hombro", intCantPress, 0);
          
       }
        String nombreRutina=txtNombreRutina.getText().trim();
       if(nuevaRutina.getCantidadEnLista()==0){
           JOptionPane.showMessageDialog(null, "No puede crear una rutina sin almenos un ejercicio", "No se creó rutina", JOptionPane.WARNING_MESSAGE);
       }else if("".equals(nombreRutina)){
            JOptionPane.showMessageDialog(null, "La rutina debe tener un nombre", "No se creó rutina", JOptionPane.WARNING_MESSAGE);
        }else{
          nUsuario.addRutina(nuevaRutina);
         
          File link= new File("usuariosRegistrados.txt");
          
          
           try {
              ObjectInputStream lector = new ObjectInputStream(new FileInputStream(link));
                    
                LinkedList<Usuarios> usuarios= (LinkedList<Usuarios>) lector.readObject();
                
                for(Usuarios u: usuarios){
                    if(u.getUsuario().equals(nUsuario.getUsuario())){
                        u.addRutina(nuevaRutina);
                    }
                }
                ObjectOutputStream escritor = new ObjectOutputStream(new FileOutputStream(link));
                escritor.writeObject(usuarios);
               
           } catch (IOException | ClassNotFoundException e) {
               Logger.getLogger(CrearRutinaFrame.class.getName()).log(Level.SEVERE, null, e);
           }
          
          JOptionPane.showMessageDialog(null, "Rutina creada correctamente");
          txtAbdominales.setSelected(false);
          txtJalon.setSelected(false);
          txtPlancha.setSelected(false);
          txtPress.setSelected(false);
          txtNombreRutina.setText("");
       }
      
    }//GEN-LAST:event_botonCreaRutinaActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        MenuUsuario menu= new MenuUsuario(nUsuario);
        menu.setVisible(true);
                       
    }//GEN-LAST:event_botonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCreaRutina;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton btAbdominales;
    private javax.swing.JButton btJalon;
    private javax.swing.JButton btPlancha;
    private javax.swing.JButton btPress;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox txtAbdominales;
    private javax.swing.JCheckBox txtJalon;
    private javax.swing.JTextField txtNombreRutina;
    private javax.swing.JCheckBox txtPlancha;
    private javax.swing.JCheckBox txtPress;
    // End of variables declaration//GEN-END:variables
    static Usuarios nUsuario= new Usuarios();
    int intCantAbdominales;
    int intCantPress;
    int intCantJalon;
    int intTiemPlancha;
}
